```toml
spin_manifest_version = 2

[application]
name = "hellorustwasm"
version = "0.1.0"
authors = ["Akram Naul"]
description = "Hello World Rust WebAssembly application"

[[trigger.http]]
route = "/..."
component = "hellorustwasm"

[component.hellorustwasm]
source = "target/wasm32-wasi/release/hellorustwasm.wasm"
allow_outbound_hosts = []

[component.hellorustwasm.build]
command = "cargo build --target wasm32-wasi --release"
watch = [
    "src/**/*.rs",
    "Cargo.toml",
    "spin.toml"
]
```
