```yaml
name: Deploy Rust WASM to Fermyon Cloud

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  spin:
    runs-on: ubuntu-latest

    name: Build and deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1

      - name: Build and deploy to Fermyon Cloud
        uses: fermyon/actions/spin/deploy@v1
        with:
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
```
